module.exports = (function() {
var __MODS__ = {};
var __DEFINE__ = function(modId, func, req) { var m = { exports: {}, _tempexports: {} }; __MODS__[modId] = { status: 0, func: func, req: req, m: m }; };
var __REQUIRE__ = function(modId, source) { if(!__MODS__[modId]) return require(source); if(!__MODS__[modId].status) { var m = __MODS__[modId].m; m._exports = m._tempexports; var desp = Object.getOwnPropertyDescriptor(m, "exports"); if (desp && desp.configurable) Object.defineProperty(m, "exports", { set: function (val) { if(typeof val === "object" && val !== m._exports) { m._exports.__proto__ = val.__proto__; Object.keys(val).forEach(function (k) { m._exports[k] = val[k]; }); } m._tempexports = val }, get: function () { return m._tempexports; } }); __MODS__[modId].status = 1; __MODS__[modId].func(__MODS__[modId].req, m, m.exports); } return __MODS__[modId].m.exports; };
var __REQUIRE_WILDCARD__ = function(obj) { if(obj && obj.__esModule) { return obj; } else { var newObj = {}; if(obj != null) { for(var k in obj) { if (Object.prototype.hasOwnProperty.call(obj, k)) newObj[k] = obj[k]; } } newObj.default = obj; return newObj; } };
var __REQUIRE_DEFAULT__ = function(obj) { return obj && obj.__esModule ? obj.default : obj; };
__DEFINE__(1629442488344, function(require, module, exports) {
!function(t,e){"object"==typeof exports&&"undefined"!=typeof module?module.exports=e():"function"==typeof define&&define.amd?define(e):t.wxComputed=e()}(this,function(){let t=0;class e{constructor(){this.subs=[],this.did=++t}addSub(t){this.subs.push(t)}depend(){e.target&&e.target.addDep(this)}notify(){this.subs.forEach(t=>t.update())}}function n(t){!function t(n){"object"==typeof n&&null!==n&&Object.keys(n).forEach(o=>{let s=n[o];const i=new e;Object.defineProperty(n,o,{set(t){s=t,i.notify()},get:()=>(i.depend(),s)}),t(s)})}(t.data)}e.target=null;let o=0;class s{constructor(t,n,s){this.vm=t,this.fn=n,this.cb=s,this.wid=++o,this.depIdMap={},this.value=this.getValue(),this.dep=new e}getValue(){e.target=this;const t=this.fn.call(this.vm);return e.target=null,t}update(){this.value=this.getValue(),"function"==typeof this.cb&&this.cb.call(this.vm),this.dep.notify()}addDep(t){this.depIdMap.hasOwnProperty(t.did)||(t.addSub(this),this.depIdMap[t.did]=t)}depend(){this.dep.depend()}}return function(t){(function(t){const{computed:e}=t,n="object"!=typeof t.computed,o=!Object.keys(e).length;if(e&&!n&&!o)return!0;console.warn("没有computed属性或computed属性不是object")})(t)&&(n(t),function(t){const e={};for(const n in t.computed){const o=t.computed[n];if("function"!=typeof o){console.warn(`${n} prop not a function in computed!!!`);break}Object.defineProperty(t.data,n,{set:function(){},get:function(){const e=new s(t,o,()=>{t.setData({[n]:e.value})});return t.data[n]=e.value,function(){return e.depend(),e.value}}()}),e[n]=t.data[n]}t.setData(e)}(t))}});

}, function(modId) {var map = {}; return __REQUIRE__(map[modId], modId); })
return __REQUIRE__(1629442488344);
})()
//miniprogram-npm-outsideDeps=[]
//# sourceMappingURL=index.js.map